repos:
# Official pre-commit out-of-box hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-added-large-files
    - id: check-yaml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: trailing-whitespace
# Golang linters aggregator
# See https://golangci-lint.run/usage/linters/ for supported linters
- repo: https://github.com/golangci/golangci-lint
  rev: v1.59.0
  hooks:
    - id: golangci-lint
# Commit messages checker
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.2.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: [--strict]
# Documentation linter
# Configuration specified in .markdownlint.yaml in each repository
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.40.0
  hooks:
    - id: markdownlint
# Renovate configuration validator
- repo: https://github.com/renovatebot/pre-commit-hooks
  rev: 37.381.2
  hooks:
    - id: renovate-config-validator
