name: build-charm
on:
  workflow_call:
    inputs:
      use-charmcraftcache:
        description: Enable usage of charmcraftcache
        required: false
        default: false
        type: boolean
      charmcraft-channel:
        description: Snap channel for charmcraft
        required: false
        default: latest/stable
        type: string
      architecture:
        description: Target architecture to build for (e.g. amd64 or arm64)
        required: false
        default: amd64
        type: string
      runner:
        description: Override the runner to run on. If empty, standard native runners are used.
        required: false
        default: ""
        type: string
    outputs:
      name:
        description: The charm name
        value: ${{ jobs.build.outputs.name }}
      platforms:
        description: The platforms for which the charm has been built
        value: ${{ jobs.build.outputs.platforms }}
      charm-paths:
        description: The paths to all the charms built
        value: ${{ jobs.build.outputs.paths }}
      artifacts-key:
        description: Key used to upload all the charm artifacts
        value: ${{ jobs.build.outputs.artifacts }}

jobs:
  build:
    runs-on: ${{ inputs.runner != '' && inputs.runner || (inputs.architecture == 'arm64' && 'self-hosted-linux-arm64-noble-medium' || 'ubuntu-latest') }}
    outputs:
      name: ${{ steps.get-charm-info.outputs.charm-name }}
      platforms: ${{ steps.get-charm-info.outputs.charm-platforms }}
      paths: ${{ steps.get-charm-paths.outputs.charm-paths }}
      artifacts: ${{ steps.artifact-name.outputs.artifact }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Setup lxd
        uses: canonical/setup-lxd@a3c85fc6fb7fff43fcfeae87659e41a8f635b7dd # v0.1.3
        with:
          channel: latest/stable
      - name: Install charmcraft
        run: |
          sudo snap install charmcraft --classic --channel ${{ inputs.charmcraft-channel }}
          if ! command -v yq &> /dev/null; then
            sudo snap install yq
          fi
          if ! command -v jq &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y jq
          fi
          echo CHARMCRAFT_BIN=charmcraft >> $GITHUB_ENV
      - name: Install charmcraftcache
        if: ${{ inputs.use-charmcraftcache }}
        run: |
          if ! command -v pipx &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y pipx
          fi
          pipx install charmcraftcache
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo CHARMCRAFT_BIN=ccc >> $GITHUB_ENV
      - name: Build charm
        run: ${{ env.CHARMCRAFT_BIN}} pack -v
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Get charm info
        id: get-charm-info
        run: |
          echo charm-name=$(cat charmcraft.yaml | yq '.name') >> $GITHUB_OUTPUT
          echo charm-platforms=$(cat charmcraft.yaml | yq '.platforms | keys | tojson') >> $GITHUB_OUTPUT
      - name: Get charm paths
        id: get-charm-paths
        run: |
          echo charm-paths=$(echo '${{ steps.get-charm-info.outputs.charm-platforms }}' | jq -r --arg charm ${{ steps.get-charm-info.outputs.charm-name }} --arg arch ${{ inputs.architecture }} 'map(select(contains($arch))) | .[] |= split(":") | .[] |= join("-", .) | map($charm + "_" + . + ".charm") | join(",")') >> $GITHUB_OUTPUT
      - id: artifact-name
        run: echo artifact='${{ github.sha }}-${{ github.job }}-${{ inputs.architecture }}' >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ steps.artifact-name.outputs.artifact }}
          path: ${{ github.workspace }}/*.charm
