name: Quality Checks

on:
  workflow_call:
    inputs:
      charm-name:
        description: Name of the charmed application the tests are running for
        required: false
        type: string
      container-name:
        description: Name of the application container to get logs from
        required: false
        type: string
      charm-config-path:
        description: Path to the application config file
        required: false
        type: string
      use-charmcraftcache:
        description: Enable usage of charmcraftcache
        required: false
        default: false
        type: boolean
    secrets:
      CHARMCRAFT_CREDENTIALS:
        required: false

jobs:
  linting:
    name: Linting
    uses: ./.github/workflows/_charm-linting.yaml

  unit-test:
    name: Unit Tests
    uses: ./.github/workflows/_charm-tests-unit.yaml
    needs:
      - linting

  integration-test:
    name: Integration Tests
    uses: ./.github/workflows/_charm-tests-integration.yaml
    with:
      charm-name: ${{ inputs.charm-name }}
      container-name: ${{ inputs.container-name }}
      charm-config-path: ${{ inputs.charm-config-path }}
      use-charmcraftcache: ${{ inputs.use-charmcraftcache }}
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
    needs:
      - linting
      - unit-test
