name: Quality Checks

on:
  workflow_call:

jobs:
  linting:
    name: Linting
    uses: ./.github/workflows/_charm-linting.yaml

  unit-test:
    name: Unit Tests
    uses: ./.github/workflows/_charm-tests-unit.yaml
    needs:
      - linting

  integration-test:
    name: Integration Tests
    uses: ./.github/workflows/_charm-tests-integration.yaml
    needs:
      - linting
      - unit-test
