name: Unit Tests

on:
  workflow_call:
    inputs:
      tox-unit-test-targets:
        description: Comma separated list of tox targets needed to perform unit-tests
        type: string
        required: false
        default: unit
      base:
        description: Ubuntu base to run unit tests on (e.g. 22.04, 24.04, 26.04)
        type: string
        required: false
        default: "22.04"

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-${{ inputs.base }}
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: ${{ inputs.base == '26.04' && '3.14' || inputs.base == '24.04' && '3.12' || '3.10' }}

      - name: Install dependencies
        run: python3 -m pip install tox

      - name: Run unit tests
        run: |
          tox -e "${{ inputs.tox-unit-test-targets }}" \
            --override "testenv:build-prerequisites.base_python=python3" \
            --override "testenv:unit.base_python=python3"
