name: Build rock

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get rock name
        id: rock_name
        run: |
          echo "name=$(yq '.name' rockcraft.yaml)" >> "$GITHUB_OUTPUT"

      - uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft_build

      - name: Generate SBOMs (Software Bill of Materials)
        env:
          ROCK: ${{ steps.rockcraft_build.outputs.rock }}
          ROCK_NAME: ${{ steps.rock_info.outputs.rock_name }}
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          syft ${{ env.ROCK }} -o spdx-json=${{ env.ROCK_NAME }}.sbom.json

      - name: Upload SBOMs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ env.ROCK_NAME }}-sbom
          path: "${{ env.ROCK_NAME }}.sbom.json"
        env:
          ROCK_NAME: ${{ steps.rock_info.outputs.rock_name }}

      - name: Upload rock
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: rock
          path: ${{ env.ROCK }}
        env:
          ROCK: ${{ steps.rockcraft_build.outputs.rock }}
