name: image scan
run-name: Scanning image ${{ inputs.image }}

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
        description: "image to scan"
      exit-code:
        type: string
        required: false
        default: "0"
        description: "Exit code when vulnerabilities are found ('1' to fail on CVEs, '0' to report only)"
      severity:
        type: string
        required: false
        default: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
        description: "Severities of CVEs to evaluate (note: unselected severities will be omitted from the uploaded SARIF report)"
      ignore-unfixed:
        type: boolean
        required: false
        default: false
        description: "Ignore unpatched CVEs without available upstream fixes"
      trivyignores:
        type: string
        required: false
        default: ""
        description: "Path to .trivyignore file"
jobs:
  scan:
    permissions:
      packages: read
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ inputs.trivyignores != '' }}
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: ${{ inputs.image }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: ${{ inputs.severity }}
          exit-code: ${{ inputs.exit-code }}
          ignore-unfixed: ${{ inputs.ignore-unfixed }}
          trivyignores: ${{ inputs.trivyignores }}

      - name: Upload scan results to GitHub
        if: always()
        uses: github/codeql-action/upload-sarif@1190a975f95ce23525efb6a3fc21ea29567c1b52 # v3
        with:
          sarif_file: 'trivy-results.sarif'
