name: Lint rockcraft.yaml

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Install yamllint
        run: |
          python3 -m pip install yamllint

      - name: YAML linting
        run: |
          yamllint --no-warnings rockcraft.yaml
