name: Publish rock to GitHub Container Registry

on:
  workflow_call:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install skopeo and yq
        run: |
          sudo snap install --devmode --channel edge skopeo
          sudo snap install yq

      - name: Download rock
        uses: actions/download-artifact@v4.1.7
        with:
          name: rock

      - name: Push image to GitHub container registry
        env:
          ROCK_NAME: $(yq '.name' rockcraft.yaml)
          ROCK_VERSION: $(yq '.version' rockcraft.yaml)
        run: |
          ROCK_FILE=$(ls *.rock | tail -n 1)
          sudo skopeo \
            --insecure-policy \
            copy \
            oci-archive:"${ROCK_FILE}" \
            docker-daemon:"ghcr.io/canonical/${ROCK_NAME}:${ROCK_VERSION}"
          docker push ghcr.io/canonical/${ROCK_NAME}:${ROCK_VERSION}
