name: image scan
run-name: Scanning image ${{ inputs.image }}

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
        description: "image to scan"
jobs:
  scan:
    permissions:
      packages: read
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: ${{ inputs.image }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload scan results to GitHub
        uses: github/codeql-action/upload-sarif@dd903d2e4f5405488e5ef1422510ee31c8b32357 # v3
        with:
          sarif_file: 'trivy-results.sarif'
