name: secscan
on:
  workflow_call:
    inputs:
      artifacts-type:
        description: Type of the artifacts, parameter to be used by secscan type modifier
        required: false
        default: package
        type: string
      artifacts-format:
        description: Format of the artifacts, parameter to be used by secscan format modifier
        required: true
        type: string
      artifacts-key:
        description: Key where the artifacts have been uploaded.
        required: true
        type: string
      artifact-paths:
        description: Paths where the artifact have been uploaded. String formatted as a JSON array
        required: true
        type: string

permissions:
  contents: read  # Required to check out repository code
  issues: write

jobs:
  inputs-vetting:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.parse.outputs.paths }}
    steps:
      - id: parse
        run: echo paths=$(echo ${{inputs.artifact-paths }} | jq -R -r '. | split(",")') >> $GITHUB_OUTPUT
  secscan:
    needs: inputs-vetting
    strategy:
      matrix:
        artifact: ${{ fromJson(needs.inputs-vetting.outputs.paths) }}
    runs-on: [self-hosted-linux-amd64-noble-private-endpoint-medium]
    steps:
      - name: Install secscan cli
        run: |
          sudo snap install canonical-secscan-client
          sudo snap connect canonical-secscan-client:home system:home

      - name: Download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ${{ inputs.artifacts-key }}

      - name: Run secscan
        id: secscan
        continue-on-error: true
        run: |
          # Ensure we capture the output even if the command fails
          secscan-client submit --scanner trivy \
            --type ${{ inputs.artifacts-type }} \
            --format ${{ inputs.artifacts-format }} \
            --token ~/snap/canonical-secscan-client/common/secscan.token \
            ${{ matrix.artifact }} --wait-and-print --raw 2>&1 | tee secscan.result
            
            echo "secscan-result=secscan.result" >> $GITHUB_OUTPUT

      - name: Upload Scan Results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: secscan-report-${{ matrix.artifact }}
          path: secscan.result

      - name: Create issue
        if: steps.secscan.outcome != 'success'
        run: |
          cat ${{ steps.secscan.outputs.secscan-result }}
          echo "please check job ${{ github.run_id}}" >> ${{ steps.secscan.outputs.secscan-result}}
          gh issue create -R ${{ github.repository }} --label bug --title "Release compromised by CVE" -F ${{ steps.secscan.outputs.secscan-result}}
        env:
          GH_TOKEN: ${{ github.token }}
          # enhance the above with actions/github-script@v7
