name: Release Charm Libraries

on:
  workflow_call:
    secrets:
      CHARMCRAFT_CREDENTIALS:
        required: true
      PAT_TOKEN:
        required: true

jobs:
  release-libs:
    name: Release Charm Libraries
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0

      - name: Release bumped charm library
        uses: canonical/charming-actions/release-libraries@9180b22741d2349858e35e1dcc2fe4e11c3ebf2d # main
        with:
          credentials: "${{ secrets.CHARMCRAFT_CREDENTIALS }}"
          github-token: "${{ secrets.PAT_TOKEN }}"
